apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ufpa-cacerts-job
  namespace: ufpa-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: ufpa-cacerts-job
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/fabric-cacerts-gen
  values:
    metadata:
      name: ufpa
      component_name: ufpa-net
      namespace: ufpa-net    
      images:
       alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
    vault:
      role: vault-role
      address: http://10.126.1.224:8200
      authpath: localufpa
      secretcryptoprefix: secretsv2/data/ufpa/ordererOrganizations/ufpa-net/ca
      secretcredentialsprefix: secretsv2/data/ufpa/credentials/ufpa-net/ca/ufpa
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: ""
      
    ca:
      subject: /C=GB/ST=London/L=London/O=Orderer/CN=ca.ufpa-net
